name: Check for New PRs and Send Notification

on:
  schedule:
    - cron: '*/15 * * * *'
  pull_request:
    branches:
      - test-pr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run email notification script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          chmod +x ./sendMail.sh
          ./sendMail.sh "$TOKEN" "$SMTP_USER" "$SMTP_PASS"
