name: CI

on:
  push:
    branches:
      - test-pr  # Trigger workflow only on push to the test-pr branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Specify the distribution (e.g., temurin, zulu, etc.)

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run email notification script
        env:
          GITHUB_TOKEN: ${{ secrets.Token }}  # Reference the secret named 'Token'
        run: |
          chmod +x ./sendMail.sh  # Make the script executable
          ./sendMail.sh "$GITHUB_TOKEN"  # Call the script with the token as an argument
